import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import ReduxProvider from "@/app/store/Provider";
import AlertUI from "./components/AlertUI";
export const metadata: Metadata = {
  title: "web tutorials",
  description: "Generated by cold",
};

const RootLayout: React.FC<Readonly<{ children: React.ReactNode }>> = ({
  children,
}) => {
  return (
    <html lang="en">
      <body className="bg-gray-50 text-gray-900 flex flex-col min-h-screen">
        <ReduxProvider>
          <AlertUI />
          <Navbar />
          <main className="flex-1 container mx-auto p-6">{children}</main>
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
};

export default RootLayout;
