import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import { Topic } from "@/model/model";
import { bbsApi } from "@/app/api/bbsAPI";
import Contorl from "./control";
import Navbar from "./navbar";
import Footer from "./footer"; // Footer 임포트

export const metadata: Metadata = {
  title: "web tutorials",
  description: "Generated by cold",
};

const RootLayout: React.FC<Readonly<{ children: React.ReactNode }>> = async ({
  children,
}) => {
  const resp = await bbsApi.getBbsList();
  const topics = await resp.data;

  return (
    <html lang="en">
      <body className="bg-gray-50 text-gray-900 flex flex-col min-h-screen">
        {/* 네비게이션 바 */}
        <Navbar />

        <div className="container mx-auto px-4 py-8 flex-grow">
          {/* 타이틀 */}
          <h1 className="text-4xl font-bold text-center text-blue-600 mb-8">
            <Link href="/">WEB Tutorials</Link>
          </h1>

          {/* 게시판 목록 */}
          <ol className="list-decimal pl-6 space-y-4">
            {topics.map((topic: Topic) => (
              <li key={topic.id} className="text-xl">
                <Link
                  href={`/read/${topic.id}`}
                  className="text-blue-500 hover:text-blue-700"
                >
                  {topic.title}
                </Link>
              </li>
            ))}
          </ol>

          <div className="my-8 border-t border-gray-300" />

          {/* 자식 컴포넌트 */}
          {children}

          <div className="my-8 border-t border-gray-300" />

          {/* 컨트롤 */}
          <Contorl />
        </div>

        {/* 푸터 추가 */}
        <Footer />
      </body>
    </html>
  );
};

export default RootLayout;