import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./navbar";
import Footer from "./footer";

export const metadata: Metadata = {
  title: "web tutorials",
  description: "Generated by cold",
};

const RootLayout: React.FC<Readonly<{ children: React.ReactNode }>> = ({
  children,
}) => {
  return (
    <html lang="en">
      <body className="bg-gray-50 text-gray-900 flex flex-col">
        <Navbar />
        <main className="max-w-7xl mx-auto flex justify-between items-center">{children}</main>
        <Footer />
      </body>
    </html>
  );
};

export default RootLayout;